name: Auto PR

on:
  push:
    branches:
      - dev

jobs:
  handle_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get committer username and email
      run: |
        echo "committer_username=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
        echo "committer_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

    - name: Set PR branch name
      run: echo "pr_branch=dev_pr_${{ env.committer_username }}" >> $GITHUB_ENV

    - name: Configure git
      run: |
        git config --global user.name "${{ env.committer_username }}"
        git config --global user.email "${{ env.committer_email }}"

    - name: Check if PR branch exists
      id: check_branch
      run: |
        if git show-ref --verify --quiet refs/heads/${{ env.pr_branch }}; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branch_exists=false" >> $GITHUB_ENV
        fi

    - name: Get existing PR number
      id: get_pr_number
      if: env.branch_exists == 'true'
      run: |
        pr_number=$(gh pr list --state open --head ${{ env.pr_branch }} --json number -q '.[0].number')
        echo "pr_number=$pr_number" >> $GITHUB_ENV

    - name: Sync commits to existing PR branch
      if: env.branch_exists == 'true'
      run: |
        git push origin HEAD:refs/heads/${{ env.pr_branch }}

    - name: Create new branch
      if: env.branch_exists == 'false'
      run: |
        git checkout -b ${{ env.pr_branch }}
        git push origin ${{ env.pr_branch }}

    - name: Create Pull Request
      if: env.branch_exists == 'false'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.pr_branch }}
        base: main
        title: "Auto PR from ${{ env.pr_branch }}"
        body: "This is an automated PR created from ${{ env.pr_branch }}"

    - name: Append commit to existing PR
      if: env.branch_exists == 'true'
      run: |
        gh pr comment ${{ env.pr_number }} --body "New commits have been added to the PR."
