# .github/workflows/auto-pr.yml
name: Auto PR

on:
  push:
    branches:
      - dev

jobs:
  handle_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get committer username and email
      run: |
        committer_username=$(git log -1 --pretty=format:'%an')
        committer_email=$(git log -1 --pretty=format:'%ae')
        echo "committer_username=$committer_username" >> $GITHUB_ENV
        echo "committer_email=$committer_email" >> $GITHUB_ENV

    - name: Hash committer username
      run: |
        branch_name=$(echo -n "${{ env.committer_username }}" | md5sum | awk '{ print $1 }')
        echo "branch_name=dev_pr_$branch_name" >> $GITHUB_ENV
        echo "Branch name: ${{ env.branch_name }}"

    - name: Configure git
      run: |
        git config --global user.name "${{ env.committer_username }}"
        git config --global user.email "${{ env.committer_email }}"

    - name: Check if PR branch exists
      id: check_branch
      run: |
        if git show-ref --verify --quiet refs/heads/${{ env.branch_name }}; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branch_exists=false" >> $GITHUB_ENV
        fi

    - name: Fetch and merge remote branch
      if: env.branch_exists == 'true'
      run: |
        git fetch origin
        git checkout ${{ env.branch_name }}
        git pull origin ${{ env.branch_name }} --rebase
        git push origin HEAD:refs/heads/${{ env.branch_name }}

    - name: Create new branch
      if: env.branch_exists == 'false'
      run: |
        git checkout -b ${{ env.branch_name }}
        git push origin ${{ env.branch_name }}

    - name: Create Pull Request
      if: env.branch_exists == 'false'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.branch_name }}
        base: main
        title: "Auto PR from ${{ env.branch_name }}"
        body: "This is an automated PR created from ${{ env.branch_name }}"

    - name: Append commit to existing PR
      if: env.branch_exists == 'true'
      run: |
        gh pr comment ${{ env.pr_number }} --body "New commits have been added to the PR."
