name: "IssueOps"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: github/command@main
        id: command
        with:
          command: ".ping_staff"
          allowed_contexts: "pull_request,issue"
          reaction: "eyes"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
            payload: |
                {
                    "blocks": [
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": "# Mentioned - Urgent Processing"
                            }
                        },
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": "*User* \n <${{ github.event.comment.user.name }}|${{ github.event.comment.user.url }}>"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "*Issue/PR* \n #<${{ github.event.issue.number }}|>${{ github.event.issue.url }}"
                                }
                            ]
                        },
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": "Github Link:"
                            },
                            "accessory": {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "Click Me"
                                },
                                "value": "link",
                                "url": "${{ github.event.comment.url }}",
                                "action_id": "button-action"
                            }
                        }
                    ]
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Success.

            > *I am a robot and this action was performed automatically.*